export const countries = [
    {countryName : 'Moscow', gmt: 3,},
    {countryName : 'Paris', gmt: 2, },
    {countryName : 'Berlin', gmt: 2, },
    {countryName : 'Brussels', gmt: 2, },
    {countryName : 'Amsterdam', gmt: 2, },
    {countryName : 'Rome', gmt: 2,},
    {countryName : 'London', gmt: 1,},
    {countryName : 'Dublin', gmt: 1,},
    {countryName : 'New York', gmt: -4, },
    {countryName : 'Washington, gmt: }, DC', gmt: -4, },
    {countryName : 'St. Louis',  gmt: -5,},
    {countryName : 'Los Angeles', gmt:-7},
    {countryName : 'Tokyo', gmt: 9},
    {countryName : 'Beijing',gmt: 8,},
    {countryName : 'Ho Chi Mihn City',  gmt: 7,},
    {countryName : 'Mumbai', gmt: 5,  },
]